Even provide the full path to the glpk lib and it still breaks compile for me with;
/home/kde4/svn/_src/koffice/krita/plugins/viewplugins/painterlymixer/kis_ks_colorspace.cpp:110: undefined reference to `glp_lpx_create_prob()'

what seems to be more then illogical :-/


svn path=/trunk/koffice/; revision=692556